(function(g){var window=this;var Cqa=function(a,b){return g.Sb(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.F)()).toString(36));
return a},b6=function(a,b,c){g.Ha(c)||(c=[String(c)]);
g.Qm(a.A,b,c)},Dqa=function(a,b){var c=[];
g.gk(b,function(d){try{var e=g.Cn.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Bn(e)&&c.push(d)},a);
return c},Eqa=function(a,b){var c=Dqa(a,b);
(0,g.y)(c,function(d){g.Cn.prototype.remove.call(this,d)},a)},Fqa=function(a){if(a.jd){if(a.jd.locationOverrideToken)return{locationOverrideToken:a.jd.locationOverrideToken};
if(null!=a.jd.latitudeE7&&null!=a.jd.longitudeE7)return{latitudeE7:a.jd.latitudeE7,longitudeE7:a.jd.longitudeE7}}return null},Gqa=function(a,b){g.Ya(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},Hqa=function(a,b){var c=b instanceof g.vc?b:g.zc(b,/^data:image\//i.test(b));
a.src=g.wc(c)},d6=function(){},Iqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Jqa=function(a){if(a.qd&&"function"==typeof a.qd)return a.qd();
if("string"===typeof a)return a.split("");if(g.Ia(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ob(a)},Kqa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ia(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.ce&&"function"==typeof a.ce)var c=a.ce();else if(a.qd&&"function"==typeof a.qd)c=void 0;else if(g.Ia(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Pb(a);d=Jqa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Lqa=function(a,b,c,d){var e=new g.Em(null,void 0);
a&&g.Fm(e,a);b&&g.Gm(e,b);c&&g.Hm(e,c);d&&(e.u=d);return e},e6=function(a,b){g.yo[a]=!0;
var c=g.wo();c&&c.publish.apply(c,arguments);g.yo[a]=!1},f6=function(a){try{var b=(0,g.yx)(),c=(0,g.xx)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Mqa=function(){var a=(0,g.xx)();
a&&Eqa(a,a.o.tf(!0))},g6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.A=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Bm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Nqa(this,a.capabilities||""),Oqa(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Nqa=function(a,b){a.capabilities.clear();
(0,g.Rd)(b.split(","),g.Oa(Cqa,Pqa)).forEach(function(c){a.capabilities.add(c)})},Oqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},h6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},i6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Qqa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Rqa=function(a){return new h6(a)},Sqa=function(a){return g.Ha(a)?(0,g.G)(a,Rqa):[]},j6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},k6=function(a){return g.Ha(a)?"["+(0,g.G)(a,j6).join(",")+"]":"null"},l6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Tqa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},m6=function(a,b){return g.Va(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},n6=function(a,b){return g.Va(a,function(c){return i6(c,b)})},o6=function(){var a=g.Ax("yt-remote-connected-devices")||[];
g.ob(a);return a},Uqa=function(a){if(g.Za(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Vqa=function(a){g.zx("yt-remote-connected-devices",a,86400)},q6=function(){if(p6)return p6;
var a=g.Ax("yt-remote-device-id");a||(a=l6(),g.zx("yt-remote-device-id",a,31536E3));for(var b=o6(),c=1,d=a;g.Ya(b,d);)c++,d=a+"#"+c;return p6=d},r6=function(){var a=o6(),b=q6();
g.Ya(a,b);g.fN()&&g.qb(a,b);a=Uqa(a);if(g.Za(a))try{g.Er("remote_sid")}catch(c){}else try{g.Dr("remote_sid",a.join(","),-1)}catch(c){}},Wqa=function(){return g.Ax("yt-remote-session-browser-channel")},Xqa=function(){return g.Ax("yt-remote-local-screens")||[]},Yqa=function(){g.zx("yt-remote-lounge-token-expiration",!0,86400)},Zqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(Xqa(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.mi)(c,function(d){return!g.Ya(b,d)})&&Yqa();
g.zx("yt-remote-local-screens",a,31536E3)},$qa=function(a,b){g.zx("yt-remote-session-browser-channel",a);
g.zx("yt-remote-session-screen-id",b);var c=o6(),d=q6();g.Ya(c,d)||c.push(d);Vqa(c);r6()},s6=function(a){a||(f6("yt-remote-session-screen-id"),f6("yt-remote-session-video-id"));
r6();a=o6();g.bb(a,q6());Vqa(a)},ara=function(){if(!t6){var a=g.Mn();
a&&(t6=new g.wn(a))}return t6?!!t6.get("yt-remote-use-staging-server"):!1},bra=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},cra=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?dra(a.shift(),function(){u6(a)}):v6()},era=function(a){return"chrome-extension://"+a+"/cast_sender.js"},dra=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=cra();
a&&a(!1,"No cast extension found")},gra=function(){if(fra){var a=2,b=cra(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;dra("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},hra=function(){gra();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},w6=function(a,b,c){g.A.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Yc=b;this.B=(0,g.x)(this.PD,this);this.o=!1;this.u=0;this.A=this.Ga=null;this.w=[]},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Iqa(a)},y6=function(){},z6=function(){},ira=function(){},kra=function(a){return(a=jra(a))?new ActiveXObject(a):new XMLHttpRequest},jra=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.A=b;this.G=c;this.D=d||1;this.B=45E3;this.w=new g.v0(this);this.u=new g.pf;this.u.setInterval(250)},mra=function(a,b,c){a.mi=1;
a.cg=a6(b.clone());a.Fh=c;a.C=!0;lra(a,null)},B6=function(a,b,c,d,e){a.mi=1;
a.cg=a6(b.clone());a.Fh=null;a.C=c;e&&(a.vA=!1);lra(a,d)},lra=function(a,b){a.Yi=(0,g.F)();
C6(a);a.Jg=a.cg.clone();b6(a.Jg,"t",a.D);a.tl=0;a.xc=a.o.Kp(a.o.fl()?b:null);0<a.rq&&(a.Vn=new g.bl((0,g.x)(a.zB,a,a.xc),a.rq));a.w.ga(a.xc,"readystatechange",a.bN);var c=a.jh?g.Zb(a.jh):{};a.Fh?(a.Do="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.xc.send(a.Jg,a.Do,a.Fh,c)):(a.Do="GET",a.vA&&!g.Gd&&(c.Connection="close"),a.xc.send(a.Jg,a.Do,null,c));a.o.ye(1)},pra=function(a,b,c){for(var d=!0;!a.Ug&&a.tl<c.length;){var e=nra(a,c);
if(e==D6){4==b&&(a.qg=4,E6(15),d=!1);break}else if(e==ora){a.qg=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.qg=1,E6(17),d=!1);a.ze=a.ze&&d;d||(G6(a),H6(a))},nra=function(a,b){var c=a.tl,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return ora;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.tl=d+c;return e},rra=function(a,b){a.Yi=(0,g.F)();
C6(a);var c=b?window.location.hostname:"";a.Jg=a.cg.clone();$5(a.Jg,"DOMAIN",c);$5(a.Jg,"t",a.D);try{a.De=new ActiveXObject("htmlfile")}catch(n){G6(a);a.qg=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in qra)k=I6[l]=qra[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Oc(g.oc("b/12014412"),d+"</body></html>");a.De.open();a.De.write(g.Ic(c));a.De.close();a.De.parentWindow.m=(0,g.x)(a.pM,a);a.De.parentWindow.d=(0,g.x)(a.Dz,a,!0);a.De.parentWindow.rpcClose=(0,g.x)(a.Dz,a,!1);c=a.De.createElement("DIV");a.De.parentWindow.document.body.appendChild(c);d=g.yc(a.Jg.toString());d=g.Vc(g.wc(d));d=g.Oc(g.oc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Pc(c,d);a.o.ye(1)},C6=function(a){a.Nt=(0,g.F)()+a.B;
sra(a,a.B)},sra=function(a,b){if(null!=a.lj)throw Error("WatchDog timer not null");
a.lj=J6((0,g.x)(a.wM,a),b)},K6=function(a){a.lj&&(g.v.clearTimeout(a.lj),a.lj=null)},H6=function(a){a.o.pw()||a.Ug||a.o.On(a)},G6=function(a){K6(a);
g.de(a.Vn);a.Vn=null;a.u.stop();g.x0(a.w);if(a.xc){var b=a.xc;a.xc=null;b.abort();b.dispose()}a.De&&(a.De=null)},F6=function(a,b){try{a.o.xz(a,b),a.o.ye(4)}catch(c){}},ura=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;tra(a,b,function(k){k?c(!0):g.v.setTimeout(function(){ura(a,b,c,d,f)},f)})}},tra=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Hqa(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},vra=function(a){this.o=a;
this.u=new y6},wra=function(a){var b=M6(a.o,a.wj,"/mail/images/cleardot.gif");
a6(b);ura(b.toString(),5E3,(0,g.x)(a.NC,a),3,2E3);a.ye(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Dd=new A6(a,void 0,void 0,void 0),a.Dd.jh=a.oq,b=a.o,b=M6(b,b.fl()?a.Uj:null,a.qq),E6(5),!g.Ed||g.jd(10))b6(b,"TYPE","xmlhttp"),B6(a.Dd,b,!1,a.Uj,!1);else{b6(b,"TYPE","html");var c=a.Dd;a=!!a.Uj;c.mi=3;c.cg=a6(b.clone());rra(c,a)}},P6=function(a){g.De.call(this);
this.headers=new g.Bm;this.N=a||null;this.A=!1;this.U=this.o=null;this.da=this.H="";this.C=0;this.w="";this.B=this.W=this.G=this.S=!1;this.D=0;this.J=null;this.aa="";this.K=this.V=!1},xra=function(a){return g.Ed&&g.id(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},yra=function(a){return"content-type"==a.toLowerCase()},Ara=function(a,b){a.A=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.w=b;a.C=5;zra(a);Q6(a)},zra=function(a){a.S||(a.S=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Cra=function(a){if(a.A&&"undefined"!=typeof g.D0)if(a.U[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.qf(a.rw,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Mg(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Bra.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.w=l+" ["+a.getStatus()+"]";zra(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){Dra(a);
var c=a.o,d=a.U[0]?g.Ea:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Dra=function(a){a.o&&a.K&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.w=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},Era=function(a,b){this.o=a;
this.map=b;this.context=null},Fra=function(a){g.fe.call(this,"statevent",a)},Gra=function(a,b){g.fe.call(this,"timingevent",a);
this.size=b},Hra=function(a){g.fe.call(this,"serverreachability",a)},Kra=function(a){Ira(a);
if(3==a.o){var b=a.Hk++,c=a.rm.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.A,b,void 0);b.mi=2;b.cg=a6(c.clone());Hqa(new Image,b.cg.toString());b.Yi=(0,g.F)();C6(b)}Jra(a)},Lra=function(a){a.iD(1,0);
a.rm=M6(a,null,a.nq);W6(a)},Ira=function(a){a.gg&&(a.gg.abort(),a.gg=null);
a.Vb&&(a.Vb.cancel(),a.Vb=null);a.vf&&(g.v.clearTimeout(a.vf),a.vf=null);X6(a);a.wd&&(a.wd.cancel(),a.wd=null);a.mg&&(g.v.clearTimeout(a.mg),a.mg=null)},Mra=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Era(a.FI++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.wd||a.mg||(a.mg=J6((0,g.x)(a.Cz,a),0),a.di=0)},Ora=function(a,b){if(1==a.o){if(!b){a.Hk=Math.floor(1E5*Math.random());
var c=a.Hk++,d=new A6(a,"",c,void 0);d.jh=null;var e=Y6(a),f=a.rm.clone();$5(f,"RID",c);$5(f,"CVER","1");V6(a,f);mra(d,f,e);a.wd=d;a.o=2}}else 3==a.o&&(b?Nra(a,b):0==a.u.length||a.wd||Nra(a))},Nra=function(a,b){if(b)if(6<a.Vg){a.u=a.w.concat(a.u);
a.w.length=0;var c=a.Hk-1;var d=Y6(a)}else c=b.G,d=b.Fh;else c=a.Hk++,d=Y6(a);var e=a.rm.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.Ci);V6(a,e);c=new A6(a,a.A,c,a.di+1);c.jh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.wd=c;mra(c,e,d)},V6=function(a,b){if(a.Vc){var c=a.Vc.Nv();
c&&g.Ib(c,function(d,e){$5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Vg&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Vg?e:f-d;try{g.Ib(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.w=a.w.concat(a.u.splice(0,b));
return c.join("&")},Pra=function(a){a.Vb||a.vf||(a.D=1,a.vf=J6((0,g.x)(a.Bz,a),0),a.Yh=0)},Z6=function(a){if(a.Vb||a.vf||3<=a.Yh)return!1;
a.D++;a.vf=J6((0,g.x)(a.Bz,a),Qra(a,a.Yh));a.Yh++;return!0},N6=function(a,b,c){a.Bo=c;
a.Ne=b.If;a.C||Lra(a)},X6=function(a){null!=a.Zg&&(g.v.clearTimeout(a.Zg),a.Zg=null)},Qra=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Vc&&(c=null);var d=(0,g.x)(a.KN,a);c||(c=new g.Em("//www.google.com/images/cleardot.gif"),a6(c));tra(c.toString(),1E4,d)}else E6(2);Rra(a,b)},Rra=function(a,b){a.o=0;
a.Vc&&a.Vc.av(b);Jra(a);Ira(a)},Jra=function(a){a.o=0;
a.Ne=-1;if(a.Vc)if(0==a.w.length&&0==a.u.length)a.Vc.Cp();else{g.eb(a.w);var b=g.eb(a.u);a.w.length=0;a.u.length=0;a.Vc.Cp(b)}},M6=function(a,b,c){var d=g.Mm(c);
if(""!=d.o)b&&g.Gm(d,b+"."+d.o),g.Hm(d,d.B);else{var e=window.location;d=Lqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ij&&g.Ib(a.Ij,function(f,k){$5(d,k,f)});
$5(d,"VER",a.Vg);V6(a,d);return d},J6=function(a,b){if(!g.Ja(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new Fra(a7,a))},Sra=function(){},Tra=function(){this.o=[];
this.u=[]},Ura=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.J(this.gM,0,this);g.B(this,this.o);this.Yc=5E3;this.u=0;if(g.Ja(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ja(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},c7=function(a,b,c){this.J=a;
this.C=b;this.A=new g.vn;this.u=new b7(this.nN,this);this.o=null;this.fb=!1;this.B=null;this.H="";this.G=this.w=0;this.D=[];this.K=c||!1},Vra=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Bo,sessionId:a.o.A,arrayId:a.o.Ci}},Wra=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Ora(a.o),Kra(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Xra=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Mg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ng(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Fb(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Wg(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.w,d,!0),onError:g.Oa(a.A,e),Vd:g.Oa(a.B,e)};c&&(a.vb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.tp(b,a)},asa=function(){var a=Yra;
Zra();h7.push(a);$ra(h7)},i7=function(a,b){Zra();
var c=h7,d=bsa(a,String(b));g.Za(c)?csa(d):($ra(c),(0,g.y)(c,function(e){e(d)}))},Zra=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",h7,void 0))},csa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},$ra=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},bsa=function(a,b){var c=((0,g.F)()-dsa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.D=a;this.o=[]},esa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},fsa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Rd)(a.o,function(f){return!!m6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=esa(a,b[d])||c;return c},gsa=function(a,b){var c=a.o.length;
a.o=(0,g.Rd)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.B=b;this.A=c;this.w=d;this.u=0;this.o=null;this.Ga=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.A=a;this.u=NaN;o7(this);this.info("Initializing with "+k6(this.o))},hsa=function(a){if(a.o.length){var b=(0,g.G)(a.o,function(d){return d.id}),c=f7(a.A,"/pairing/get_lounge_token_batch");
g7(a.A,c,{screen_ids:b.join(",")},(0,g.x)(a.ZD,a),(0,g.x)(a.YD,a))}},o7=function(a){var b=Sqa(Xqa());
b=(0,g.Rd)(b,function(c){return!c.uuid});
return fsa(a,b)},q7=function(a,b){Zqa((0,g.G)(a.o,Qqa));
b&&Yqa()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.Ax("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ya(c,l)}this.o=d;this.B=a;this.A=this.w=NaN;this.u=null;r7("Initialized with "+g.Hk(this.o))},isa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Pb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Hk(a.o)),a.o=b,a.R("screenChange"));jsa(a)},u7=function(a){isNaN(a.A)||g.vo(a.A);
a.A=g.to((0,g.x)(a.Qs,a),0<a.w&&a.w<(0,g.F)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},ksa=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Kb("Requesting availability of screen w/o lounge token.")});
return b},jsa=function(a){a=g.Pb(g.Jb(a.o,function(b){return b}));
g.ob(a);a.length?g.zx("yt-remote-online-screen-ids",a.join(","),60):f6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.A=null;this.w=[];this.B={};lsa(this)},nsa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Qd();if(k=(c?n6(k,c):null)||n6(k,b)){k.uuid=b;var l=w7(a,k);isa(a.u,l,function(m){e(m?l:null)})}else c?msa(a,c,(0,g.x)(function(m){var n=w7(this,new h6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));isa(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},osa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},msa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={vb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.tp(f7(a.C,"/pairing/get_lounge_token_batch"),e)},psa=function(a){a.o=a.A.Qd();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+k6(a.o))},lsa=function(a){x7(a);
a.A=new p7(a.C);a.A.subscribe("screenChange",(0,g.x)(a.hE,a));psa(a);a.w=Sqa(g.Ax("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+k6(a.w));a.u=new s7(a.C,(0,g.x)(a.Qd,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=n6(a.w,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.w.push(b),g.zx("yt-remote-automatic-screen-cache",(0,g.G)(a.w,Qqa)));x7(a);a.B[b.uuid]=b.id;g.zx("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Ax("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.U=c;this.H=a;this.u=b;this.A=null},z7=function(a,b){i7(a.U,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.w=0;this.C=(0,g.x)(this.vO,this);this.B=(0,g.x)(this.HM,this);this.w=g.to((0,g.x)(function(){qsa(this,null)},this),12E4)},rsa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Hk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ea,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Hk(b))},qsa=function(a,b){g.vo(a.w);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.A||a.A.id!=b){var c=(0,g.x)(a.Qn,a),d=(0,g.x)(a.Ud,a);a.iw(b,c,d,5)}}else a.Ud(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.w=this.G=null;this.J="";this.N=c;this.B=null;this.D=g.Ea;this.C=NaN;this.K=(0,g.x)(this.yO,this);this.o=g.Ea},ssa=function(a){a.o=a.H.FB(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ea;
this.Qn(b)},a),(0,g.x)(function(b){this.o=g.Ea;
this.Ud(b)},a))},tsa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}ara()&&(b.env_useStageMdx=1);return g.Ug(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.to((0,g.x)(this.Di,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.D=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.A=[];this.w=(0,g.x)(this.oL,this)},usa=function(a,b){return b?g.Va(a.A,function(c){return i6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Yra=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.A.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.de(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.Az,a,b)),b.A?a.R("yt-remote-cast2-session-change",b.A):c&&a.o.Di(null)):a.R("yt-remote-cast2-session-change",null))},vsa=function(a){var b=a.u.EB(),c=a.o&&a.o.u;
a=(0,g.G)(b,function(d){c&&i6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=usa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Bsa=function(a,b,c,d,e,f,k){wsa()?xsa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?ysa(a,c):(window.__onGCastApiAvailable=function(l,m){l?ysa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),f6("yt-remote-cast-available"),f6("yt-remote-cast-receiver"),zsa(),c(!1))},d?g.Go("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?hra():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(gra(),u6(Asa.map(era))))):H7("Cannot initialize because not running Chrome")},zsa=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);Csa(!1);g.Bo(M7);M7.length=0},N7=function(){return!!g.Ax("yt-remote-cast-installed")},Dsa=function(){var a=g.Ax("yt-remote-cast-receiver");
return a?a.friendlyName:null},Esa=function(){H7("clearCurrentReceiver");
f6("yt-remote-cast-receiver")},Fsa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Ao("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},wsa=function(){var a=0<=g.Gb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Qs||a},Gsa=function(a,b){L7().init(a,b)},xsa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.zx("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.zx("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.zx("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+j6(f));
f||f6("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Da("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},ysa=function(a,b){K7(!0);
I7(!1);Gsa(a,function(c){c?(Csa(!0),g.Do("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),f6("yt-remote-cast-available"),f6("yt-remote-cast-receiver"),zsa());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.zx("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Csa=function(a){H7("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.D=0;this.o=null;this.hasNext=this.Oe=!1;this.H=this.G=this.u=this.w=0;this.A=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Oe=!1;a.hasNext=!1;a.D=0;a.C=(0,g.F)();a.w=0;a.u=0;a.G=0;a.H=0;a.A=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.F)()-a.C)/1E3:0},U7=function(a,b){a.D=b;
a.C=(0,g.F)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.F)()-a.C)/1E3+a.D;
case -1E3:return 0}return a.D},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.$b(a.o);b.hasPrevious=a.Oe;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.C;b.seekableStart=a.w;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.w=a;this.C=[];this.B=new Tra;this.A=this.u=null;this.H=(0,g.x)(this.oJ,this);this.D=(0,g.x)(this.Kk,this);this.G=(0,g.x)(this.nJ,this);this.J=(0,g.x)(this.AJ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Qt,this),Hsa(this))):c=3;0!=c&&(b?this.Qt(c):g.to((0,g.x)(function(){this.Qt(c)},this),0));
var d=Fsa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.w.getPlayerContextData())},Hsa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.w.subscribe(b,g.Oa(this.lL,b),this))},a)},Isa=function(a){(0,g.y)(a.C,function(b){this.w.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.w.sendMessage(b,c)},b8=function(a,b){Isa(a);
a.w.setPlayerContextData(X7(b));Hsa(a)},Y7=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.D),a.Kk(null));
a.A=b;a.A&&(i7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.D),a.A.media.length&&a.Kk(a.A.media[0]))},Jsa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Kb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Kb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.K=!1;this.G=this.D=this.H=this.J=NaN;this.U=[];this.w=this.C=this.A=this.Qa=this.o=null;this.S=a;this.U.push(g.hr(window,"beforeunload",(0,g.x)(this.SD,this)));this.u=[];this.Qa=new R7;this.N=b.id;this.o=Ksa(this,c);this.o.subscribe("handlerOpened",this.sJ,this);this.o.subscribe("handlerClosed",this.pJ,this);this.o.subscribe("handlerError",this.qJ,this);this.o.subscribe("handlerMessage",this.rJ,this);Xra(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.fN()&&g.zx("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},Ksa=function(a,b){return new c7(f7(a.S,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},Lsa=function(a){a.B=g.to((0,g.x)(function(){g8("Connecting timeout");
this.ci(1)},a),2E4)},i8=function(a){g.vo(a.B);
a.B=NaN},j8=function(a){g.vo(a.J);
a.J=NaN},Msa=function(a){k8(a);
a.H=g.to((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.vo(a.H);
a.H=NaN},Osa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.gw()&&a.Qa.reset(),h8(a,1),l8(a,"getNowPlaying"),Nsa(a)):a.ci(1)},Psa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Wb(b.params)?a.Qa.o=null:a.Qa.o=b.params,a.R("remotePlayerChange"))},Qsa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;W7(a.Qa,c,d);a.R("remoteQueueChange")},Ssa=function(a,b){b.params=b.params||{};
Qsa(a,b);Rsa(a,b);a.R("autoplayDismissed")},Rsa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.G=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.A=d;c.B=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.w=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Qa.playerState?Msa(a):k8(a);a.R("remotePlayerChange")},Tsa=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Qa,isNaN(c)?0:c);a.R("remotePlayerChange")}},Usa=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.R("remotePlayerChange")},Vsa=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},Wsa=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Oe="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.R("previousNextChange")},Nsa=function(a){g.vo(a.G);
a.G=g.to((0,g.x)(a.ci,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Hk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Xc=a;this.u=[];this.u.push(this.Xc.$_s("screenChange",(0,g.x)(this.tO,this)));this.u.push(this.Xc.$_s("onlineScreenChange",(0,g.x)(this.PK,this)))},ata=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ko("MDX_CONFIG")||b;Mqa();r6();n8||(n8=new e7(b?b.loungeApiHost:void 0),ara()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",o8,void 0));Xsa();var c=p8();if(!c){var d=new v7(n8);g.Da("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Bsa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Da("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Hk(b)),s8.push(g.Ao("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),s8.push(g.Ao("yt-remote-cast2-receiver-selected",function(){t8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Ao("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Ao("yt-remote-cast2-session-change",Ysa)),s8.push(g.Ao("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),Esa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.kp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Hk(a)),Zsa(a),c.start(),q8()||$sa())},cta=function(){var a=bta();
N7()&&g.Ax("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},bta=function(){var a=p8().Xc.$_gos();
var b=w8();b&&x8()&&(m6(a,b)||a.push(b));return Tqa(a)},y8=function(){var a=dta();
!a&&N7()&&Dsa()&&(a={key:"cast-selector-receiver",name:Dsa()});return a},dta=function(){var a=bta(),b=w8();
b||(b=u8());return g.Va(a,function(c){return b&&i6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().Qd();return n6(b,a)},Ysa=function(a){r8("remote.onCastSessionChange_: "+j6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},eta=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},fta=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||eta("");g.Da("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},u8=function(){var a=g.fN();
if(!a)return null;var b=p8().Qd();return n6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{eta(a.id);var c=new f8(n8,a,v8());c.connect(b,fta());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},$sa=function(){var a=u8();
a?(r8("Resume connection to: "+j6(a)),A8(a,0)):(s6(),Esa(),r8("Skipping connecting because no session screen found."))},Xsa=function(){var a=v8();
if(g.Wb(a)){a=q6();var b=g.Ax("yt-remote-session-name")||"",c=g.Ax("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Zsa=function(a){a?(g.zx("yt-remote-session-app",a.app),g.zx("yt-remote-session-name",a.name)):(f6("yt-remote-session-app"),f6("yt-remote-session-name"));
g.Da("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.A.call(this);
this.B=a;this.u=b;this.A=new g.P(this);g.B(this,this.A);this.A.M(b,"onCaptionsTrackListChanged",this.kK);this.A.M(b,"captionschanged",this.mJ);this.A.M(b,"captionssettingschanged",this.OA);this.A.M(b,"videoplayerreset",this.Rn);this.A.M(b,"mdxautoplaycancel",this.MC);this.N=this.A.M(b,"onVolumeChange",this.hz);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.wz,this);c.subscribe("remotePlayerChange",this.Nk,this);c.subscribe("remoteQueueChange",this.Rn,this);c.subscribe("autoplayUpNext",this.Xy,
this);c.subscribe("previousNextChange",this.sz,this);c.subscribe("nowAutoplaying",this.oz,this);c.subscribe("autoplayDismissed",this.Wy,this);this.suggestion=null;this.H=new g.PD(64);this.w=new g.J(this.LA,500,this);g.B(this,this.w);this.C=new g.J(this.MA,1E3,this);g.B(this,this.C);this.K=new w6(this.VN,0,this);g.B(this,this.K);this.D={};this.U=new g.J(this.rB,1E3,this);g.B(this,this.U);this.J=new g.bl(this.zG,1E3,this);g.B(this,this.J);this.S=g.Ea;this.OA();this.Rn();this.Nk()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.U=b||0;c.player.R("progresssync",b,d)},gta=function(a){H8(a,0);
a.w.stop();I8(a,new g.PD(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.bc(c,b));a.o.BA(a.u.getVideoData(1).videoId,c);a.D=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.Qe,Fqa(c));I8(a,new g.PD(1))},hta=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{jS:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.VD(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.sU(a.u.app,d);a.H=b;ita(a.B,c,b)}},M8=function(){g.S.call(this,{F:"div",
I:"ytp-mdx-popup-dialog",O:{role:"dialog"},L:[{F:"div",I:"ytp-mdx-popup-dialog-inner-content",L:[{F:"div",I:"ytp-mdx-popup-title",X:"Vous \u00eates d\u00e9connect\u00e9"},{F:"div",I:"ytp-mdx-popup-description",X:"Les vid\u00e9os que vous visionnez peuvent \u00eatre ajout\u00e9es \u00e0 l'historique des vid\u00e9os regard\u00e9es sur votre t\u00e9l\u00e9viseur et avoir une influence sur les recommandations qui vous sont faites. Pour \u00e9viter ce probl\u00e8me, annulez et connectez-vous \u00e0 YouTube sur un ordinateur."},
{F:"div",I:"ytp-mdx-privacy-popup-buttons",L:[{F:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],X:"Annuler"},{F:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],X:"Confirmer"}]}]}]});this.w=new g.lN(this,250);g.B(this,this.w);this.G=this.u["ytp-mdx-privacy-popup-cancel"];this.M(this.G,"click",this.B);this.C=this.u["ytp-mdx-privacy-popup-confirm"];this.M(this.C,"click",this.D)},N8=function(a){g.S.call(this,{F:"div",
I:"ytp-remote",L:[{F:"div",I:"ytp-remote-display-status",L:[{F:"div",I:"ytp-remote-display-status-icon",L:[g.nN()]},{F:"div",I:"ytp-remote-display-status-text",X:"{{statustext}}"}]}]});this.w=new g.lN(this,250);g.B(this,this.w);this.B=a;this.M(a,"presentingplayerstatechange",this.C);jta(this,g.jL(a))},jta=function(a,b){if(3==a.B.getPresentingPlayerType()){var c={RECEIVER_NAME:a.B.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.VN("Erreur sur $RECEIVER_NAME",c):g.WD(b)||g.W(b,4)?g.VN("Lecture sur $RECEIVER_NAME",c):g.VN("Connect\u00e9 \u00e0 $RECEIVER_NAME",c);a.A("statustext",c);a.w.show()}else a.w.hide()},O8=function(a,b){g.RP.call(this,"Lire sur",0,a,b);
this.w=a;this.G={};this.M(a,"onMdxReceiversChange",this.N);this.M(a,"presentingplayerstatechange",this.N);this.N()},P8=function(a){g.$Q.call(this,a);
this.u={key:l6(),name:"Cet ordinateur"};this.B=null;this.w=[];this.N=this.o=null;this.J=[this.u];this.A=this.u;this.D=new g.PD(64);this.U=0;this.H=-1;this.C=null;if(!g.By(this.player.P())){a=this.player;var b=g.vD(a);b&&(b=b.zk())&&(b=new O8(a,b),g.B(this,b));b=new N8(a);g.B(this,b);g.CL(a,b.element,4);this.C=new M8;g.B(this,this.C);g.CL(a,this.C.element,4);this.K=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},ita=function(a,b,c){a.D=
c;
a.player.R("presentingplayerstatechange",new g.aE(c,b))},R8=function(a,b){if(b.key!=a.A.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.T(a.player.P().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.ko("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.ko("SESSION_INDEX")&&!g.ko("LOGGED_IN")))||a.K||!a.C);if(c?0:a.player.P().lh()||"WEB_EMBEDDED_PLAYER"==a.player.P().deviceParams.c)g.WD(g.jL(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.MM,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.w.show(),x8()||(E8=!0);a.A=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);
var e=c.videoId;if(!d&&!e||(2==a.player.app.S||1==a.player.app.S)&&g.T(a.player.P().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Qe,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=Fqa(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.Hk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?e6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().Qd(),(c=n6(c,b.key))&&A8(c,1))}},qra={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},kta={},Pqa={WO:"atp",tR:"ska",iR:"que",KQ:"mus",sR:"sus",VP:"dsp",pR:"seq"};
g6.prototype.hg=function(){var a=new g6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.A=this.A;a.u=this.u;a.o=this.o};
var t6,p6="",fra=bra("loadCastFramework")||bra("loadCastApplicationFramework"),Asa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Qa(w6,g.A);g.h=w6.prototype;g.h.OD=function(a){this.w=arguments;this.o=!1;this.Ga?this.A=(0,g.F)()+this.Yc:this.Ga=g.qf(this.B,this.Yc)};
g.h.stop=function(){this.Ga&&(g.v.clearTimeout(this.Ga),this.Ga=null);this.A=null;this.o=!1;this.w=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.w)))};
g.h.Z=function(){this.stop();w6.yb.Z.call(this)};
g.h.PD=function(){this.A?(this.Ga=g.qf(this.B,this.A-(0,g.F)()),this.A=null):(this.Ga=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.w)))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},jra(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Qa(ira,z6);S8=new ira;g.h=A6.prototype;g.h.jh=null;g.h.ze=!1;g.h.lj=null;g.h.Nt=null;g.h.Yi=null;g.h.mi=null;g.h.cg=null;g.h.Jg=null;g.h.Fh=null;g.h.xc=null;g.h.tl=0;g.h.De=null;g.h.Do=null;g.h.qg=null;g.h.Vj=-1;g.h.vA=!0;g.h.Ug=!1;g.h.rq=0;g.h.Vn=null;var ora={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.bN=function(a){a=a.target;var b=this.Vn;b&&3==R6(a)?b.Hm():this.zB(a)};
g.h.zB=function(a){try{if(a==this.xc)a:{var b=R6(this.xc),c=this.xc.C,d=this.xc.getStatus();if(g.Ed&&!g.jd(10)||g.Gd&&!g.id("420+")){if(4>b)break a}else if(3>b||3==b&&!g.nh&&!T6(this.xc))break a;this.Ug||4!=b||7==c||(8==c||0>=d?this.o.ye(3):this.o.ye(2));K6(this);var e=this.xc.getStatus();this.Vj=e;var f=T6(this.xc);(this.ze=200==e)?(4==b&&G6(this),this.C?(pra(this,b,f),g.nh&&this.ze&&3==b&&(this.w.ga(this.u,"tick",this.VM),this.u.start())):F6(this,f),this.ze&&!this.Ug&&(4==b?this.o.On(this):(this.ze=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.qg=3,E6(13)):(this.qg=0,E6(14)),G6(this),H6(this))}}catch(k){this.xc&&T6(this.xc)}finally{}};
g.h.VM=function(){var a=R6(this.xc),b=T6(this.xc);this.tl<b.length&&(K6(this),pra(this,a,b),this.ze&&4!=a&&C6(this))};
g.h.pM=function(a){J6((0,g.x)(this.oM,this,a),0)};
g.h.oM=function(a){this.Ug||(K6(this),F6(this,a),C6(this))};
g.h.Dz=function(a){J6((0,g.x)(this.nM,this,a),0)};
g.h.nM=function(a){this.Ug||(G6(this),this.ze=a,this.o.On(this),this.o.ye(4))};
g.h.cancel=function(){this.Ug=!0;G6(this)};
g.h.wM=function(){this.lj=null;var a=(0,g.F)();0<=a-this.Nt?(2!=this.mi&&this.o.ye(3),G6(this),this.qg=2,E6(18),H6(this)):sra(this,this.Nt-a)};
g.h.getLastError=function(){return this.qg};g.h=vra.prototype;g.h.oq=null;g.h.Dd=null;g.h.Wn=!1;g.h.qw=null;g.h.pm=null;g.h.Uq=null;g.h.qq=null;g.h.fe=null;g.h.If=-1;g.h.Uj=null;g.h.wj=null;g.h.connect=function(a){this.qq=a;a=M6(this.o,null,this.qq);E6(3);this.qw=(0,g.F)();var b=this.o.G;null!=b?(this.Uj=b[0],(this.wj=b[1])?(this.fe=1,wra(this)):(this.fe=2,O6(this))):(b6(a,"MODE","init"),this.Dd=new A6(this,void 0,void 0,void 0),this.Dd.jh=this.oq,B6(this.Dd,a,!1,null,!0),this.fe=0)};
g.h.NC=function(a){if(a)this.fe=2,O6(this);else{E6(4);var b=this.o;b.Ne=b.gg.If;$6(b,9)}a&&this.ye(2)};
g.h.Kp=function(a){return this.o.Kp(a)};
g.h.abort=function(){this.Dd&&(this.Dd.cancel(),this.Dd=null);this.If=-1};
g.h.pw=function(){return!1};
g.h.xz=function(a,b){this.If=a.Vj;if(0==this.fe)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.Ne=this.If;$6(c,2);return}this.Uj=c[0];this.wj=c[1]}else c=this.o,c.Ne=this.If,$6(c,2);else if(2==this.fe)if(this.Wn)E6(7),this.Uq=(0,g.F)();else if("11111"==b){if(E6(6),this.Wn=!0,this.pm=(0,g.F)(),c=this.pm-this.qw,!g.Ed||g.jd(10)||500>c)this.If=200,this.Dd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.pm=this.Uq=(0,g.F)(),this.Wn=!1};
g.h.On=function(){this.If=this.Dd.Vj;if(this.Dd.ze)0==this.fe?this.wj?(this.fe=1,wra(this)):(this.fe=2,O6(this)):2==this.fe&&((!g.Ed||g.jd(10)?!this.Wn:200>this.Uq-this.pm)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.fe?E6(9):2==this.fe&&E6(10);var a=this.o;this.Dd.getLastError();a.Ne=this.If;$6(a,2)}};
g.h.fl=function(){return this.o.fl()};
g.h.isActive=function(){return this.o.isActive()};
g.h.ye=function(a){this.o.ye(a)};g.Qa(P6,g.De);var Bra=/^https?$/i,lta=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.w="";this.C=0;this.da=b;this.S=!1;this.A=!0;this.o=this.N?kra(this.N):kra(S8);this.U=this.N?this.N.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.rw,this);try{d6(S6(this,"Opening Xhr")),this.W=!0,this.o.open(b,String(a),!0),this.W=!1}catch(f){d6(S6(this,"Error opening Xhr: "+f.message));Ara(this,f);return}a=c||
"";var e=this.headers.clone();d&&Kqa(d,function(f,k){e.set(k,f)});
d=g.Va(e.ce(),yra);c=g.v.FormData&&a instanceof g.v.FormData;!g.Ya(lta,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.aa&&(this.o.responseType=this.aa);"withCredentials"in this.o&&this.o.withCredentials!==this.V&&(this.o.withCredentials=this.V);try{Dra(this),0<this.D&&(this.K=xra(this.o),d6(S6(this,"Will abort after "+this.D+"ms if incomplete, xhr2 "+this.K)),this.K?(this.o.timeout=this.D,this.o.ontimeout=(0,g.x)(this.tw,this)):this.J=g.qf(this.tw,this.D,this)),d6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){d6(S6(this,"Send error: "+f.message)),Ara(this,f)}};
g.h.tw=function(){"undefined"!=typeof g.D0&&this.o&&(this.w="Timed out after "+this.D+"ms, aborting",this.C=8,S6(this,this.w),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.A&&(S6(this,"Aborting"),this.A=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.Z=function(){this.o&&(this.A&&(this.A=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.yb.Z.call(this)};
g.h.rw=function(){this.ka()||(this.W||this.G||this.B?Cra(this):this.nL())};
g.h.nL=function(){Cra(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.w?this.w:String(this.w)};g.h=U6.prototype;g.h.Ij=null;g.h.wd=null;g.h.Vb=null;g.h.nq=null;g.h.rm=null;g.h.Ou=null;g.h.Im=null;g.h.Hk=0;g.h.FI=0;g.h.Vc=null;g.h.mg=null;g.h.vf=null;g.h.Zg=null;g.h.gg=null;g.h.Bo=null;g.h.Ci=-1;g.h.Xw=-1;g.h.Ne=-1;g.h.di=0;g.h.Yh=0;g.h.Vg=8;var a7=new g.De;g.Qa(Fra,g.fe);g.Qa(Gra,g.fe);g.Qa(Hra,g.fe);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.nq=b;this.Ij=c||{};d&&void 0!==e&&(this.Ij.OSID=d,this.Ij.OAID=e);this.C?(J6((0,g.x)(this.gv,this,a),100),Lra(this)):this.gv(a)};
g.h.gv=function(a){this.gg=new vra(this);this.gg.oq=null;this.gg.u=this.B;this.gg.connect(a)};
g.h.pw=function(){return 0==this.o};
g.h.Cz=function(a){this.mg=null;Ora(this,a)};
g.h.Bz=function(){this.vf=null;this.Vb=new A6(this,this.A,"rpc",this.D);this.Vb.jh=null;this.Vb.rq=0;var a=this.Ou.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.Bo?"0":"1");$5(a,"AID",this.Ci);V6(this,a);if(!g.Ed||g.jd(10))$5(a,"TYPE","xmlhttp"),B6(this.Vb,a,!0,this.Im,!1);else{$5(a,"TYPE","html");var b=this.Vb,c=!!this.Im;b.mi=3;b.cg=a6(a.clone());rra(b,c)}};
g.h.xz=function(a,b){if(0!=this.o&&(this.Vb==a||this.wd==a))if(this.Ne=a.Vj,this.wd==a&&3==this.o)if(7<this.Vg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Ha(c)&&3==c.length)if(0==c[0])a:{if(!this.vf){if(this.Vb)if(this.Vb.Yi+3E3<this.wd.Yi)X6(this),this.Vb.cancel(),this.Vb=null;else break a;Z6(this);E6(19)}}else this.Xw=c[1],0<this.Xw-this.Ci&&37500>c[2]&&this.Bo&&0==this.Yh&&!this.Zg&&(this.Zg=J6((0,g.x)(this.iJ,this),6E3));else $6(this,11)}else b!=kta.tP.o&&$6(this,11);else if(this.Vb==a&&
X6(this),!g.ub(b)){c=this.B.parse(b);g.Ha(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ci=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Im=e[2],e=e[3],null!=e?this.Vg=e:this.Vg=6,this.o=3,this.Vc&&this.Vc.cv(),this.Ou=M6(this,this.fl()?this.Im:null,this.nq),Pra(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Vc&&this.Vc.bv(e),this.Yh=0)}}};
g.h.iJ=function(){null!=this.Zg&&(this.Zg=null,this.Vb.cancel(),this.Vb=null,Z6(this),E6(20))};
g.h.On=function(a){if(this.Vb==a){X6(this);this.Vb=null;var b=2}else if(this.wd==a)this.wd=null,b=1;else return;this.Ne=a.Vj;if(0!=this.o)if(a.ze)1==b?(b=(0,g.F)()-a.Yi,a7.dispatchEvent(new Gra(a7,a.Fh?a.Fh.length:0,b,this.di)),W6(this),this.w.length=0):Pra(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ne)){if(d=1==b)this.wd||this.mg||1==this.o||2<=this.di?d=!1:(this.mg=J6((0,g.x)(this.Cz,this,a),Qra(this,this.di)),this.di++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.iD=function(a){if(!g.Ya(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.KN=function(a){a?E6(2):(E6(1),Rra(this,8))};
g.h.Kp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.V=!1;return a};
g.h.isActive=function(){return!!this.Vc&&this.Vc.isActive(this)};
g.h.ye=function(a){a7.dispatchEvent(new Hra(a7,a))};
g.h.fl=function(){return!(!g.Ed||g.jd(10))};
g.h=Sra.prototype;g.h.cv=function(){};
g.h.bv=function(){};
g.h.av=function(){};
g.h.Cp=function(){};
g.h.Nv=function(){return{}};
g.h.isActive=function(){return!0};g.h=Tra.prototype;g.h.isEmpty=function(){return g.Za(this.o)&&g.Za(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.Ya(this.o,a)||g.Ya(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Ana)(b,a);0<=c?(g.ab(b,c),b=!0):b=!1;return b||g.bb(this.u,a)};
g.h.qd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Qa(b7,g.A);g.h=b7.prototype;g.h.gM=function(){this.Yc=Math.min(3E5,2*this.Yc);this.A();this.u&&this.start()};
g.h.start=function(){var a=this.Yc+15E3*Math.random();g.Xm(this.o,a);this.u=(0,g.F)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Yc=5E3};g.Qa(c7,Sra);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.Ve=function(a){return this.A.kh(a)};
g.h.R=function(a,b){return this.A.R.apply(this.A,arguments)};
g.h.dispose=function(){this.fb||(this.fb=!0,g.de(this.A),Wra(this),g.de(this.u),this.u=null)};
g.h.ka=function(){return this.fb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.w=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.o;e&&(e.Vc=null);d.Vc=this;this.o=d;e?this.o.connect(a,b,this.C,e.A,e.Ci):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.bc(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.D.push(c):d7(this)&&Mra(this.o,c)};
g.h.cv=function(){this.u.reset();this.B=null;this.w=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)Mra(this.o,a[b])}this.R("handlerOpened")};
g.h.av=function(a){var b=2==a&&401==this.o.Ne;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.Cp=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Nv=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.w&&(a.ui=""+this.w);0!=this.G&&(a.ui=""+this.G);this.B&&g.bc(a,this.B);return a};
g.h.bv=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Kra(this.o)):this.R("handlerMessage",new Ura(a[0],a[1]))};
g.h.nN=function(){this.u.isActive();var a=this.o,b=0;a.Vb&&b++;a.wd&&b++;0==b&&this.connect(this.B,this.w)};e7.prototype.w=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var dsa=(0,g.F)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Qa(m7,g.Q);m7.prototype.Qd=function(){return this.o};
m7.prototype.contains=function(a){return!!m6(this.o,a)};
m7.prototype.get=function(a){return a?n6(this.o,a):null};
m7.prototype.info=function(a){i7(this.D,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ga)&&this.DB()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ga)||(g.vo(this.Ga),this.Ga=NaN)};
g.h.Z=function(){this.stop();g.Q.prototype.Z.call(this)};
g.h.DB=function(){this.Ga=NaN;this.o=g.tp(f7(this.C,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.rO,this),onError:(0,g.x)(this.qO,this),Vd:(0,g.x)(this.sO,this)})};
g.h.rO=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.w;this.R("pairingComplete",new h6(c))};
g.h.qO=function(a){this.o=null;a.status&&404==a.status?this.u>=mta.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=mta[this.u],this.Ga=g.to((0,g.x)(this.DB,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.sO=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var mta=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Qa(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.Ax("yt-remote-lounge-token-expiration")&&hsa(this);g.vo(this.u);this.u=g.to((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);esa(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||hsa(this)};
g.h.remove=function(a,b){var c=o7(this);gsa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.yo=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.Z=function(){g.vo(this.u);p7.yb.Z.call(this)};
g.h.ZD=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.D,"Missed "+b+" lounge tokens.")};
g.h.YD=function(a){i7(this.D,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Ax("yt-remote-fast-check-period")||"0",10);(this.w=(0,g.F)()-144E5<a?0:a)?u7(this):(this.w=(0,g.F)()+3E5,g.zx("yt-remote-fast-check-period",this.w),this.Qs())};
g.h.isEmpty=function(){return g.Wb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Jb(this.o,function(c,d){return c&&!!n6(a,d)},this);
t7(this,b)};
g.h.Z=function(){g.vo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.Z.call(this)};
g.h.Qs=function(){g.vo(this.A);this.A=NaN;this.u&&this.u.abort();var a=ksa(this);if(c6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Pb(a).join(",")},(0,g.x)(this.JL,this,a),(0,g.x)(this.IL,this))}else t7(this,{}),u7(this)};
g.h.JL=function(a,b){this.u=null;var c=g.Pb(ksa(this));if(g.pb(c,g.Pb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Kb("Changing Screen set during request."),this.Qs()};
g.h.IL=function(a){this.Kb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Kb=function(a){i7("OnlineScreenService",a)};g.Qa(v7,m7);g.h=v7.prototype;g.h.start=function(){this.A.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.A.add(a,b,c)};
g.h.remove=function(a,b,c){this.A.remove(a,b,c);this.u.update()};
g.h.yo=function(a,b,c,d){this.A.contains(a)?this.A.yo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.D,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.o:g.db(this.o,(0,g.Rd)(this.w,function(b){return!this.contains(b)},this))};
g.h.EB=function(){return(0,g.Rd)(this.Qd(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.FB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.de(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.de(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.uO=function(a,b,c,d){g.tp(f7(this.C,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new h6(f.screen||{});if(!k.name||osa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);osa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Vd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Z=function(){g.de(this.A);g.de(this.u);v7.yb.Z.call(this)};
g.h.hE=function(){psa(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Qa(y7,g.Q);g.h=y7.prototype;g.h.Qn=function(a){this.A=a;this.R("sessionScreen",this.A)};
g.h.Ud=function(a){this.ka()||(a&&z7(this,""+a),this.A=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.U,a)};
g.h.HB=function(){return null};
g.h.Zs=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Z=function(){this.Zs("");y7.yb.Z.call(this)};g.Qa(A7,y7);g.h=A7.prototype;g.h.Ys=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);rsa(this)};
g.h.Di=function(a){this.info("launchWithParams no-op for Cast: "+g.Hk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Ud()},this),(0,g.x)(function(){this.Ud(Error("Failed to stop receiver app."))},this)):this.Ud(Error("Stopping cast device witout session."))};
g.h.Zs=g.Ea;g.h.Z=function(){this.info("disposeInternal");g.vo(this.w);this.w=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.yb.Z.call(this)};
g.h.HM=function(a,b){if(!this.ka())if(b){var c=x6(b);if(g.La(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Hk(c));switch(d){case "mdxSessionStatus":qsa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.iw=function(a,b,c,d){nsa(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.to((0,g.x)(this.iw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.HB=function(){return this.o};
g.h.vO=function(a){this.ka()||a||(z7(this,"Cast session died."),this.Ud())};g.Qa(B7,y7);g.h=B7.prototype;g.h.Ys=function(a){this.w=a;this.w.addUpdateListener(this.K)};
g.h.Di=function(a){this.B=a;this.D()};
g.h.stop=function(){this.o();this.o=g.Ea;g.vo(this.C);this.w?this.w.stop((0,g.x)(this.Ud,this,null),(0,g.x)(this.Ud,this,"Failed to stop DIAL device.")):this.Ud()};
g.h.Z=function(){this.o();this.o=g.Ea;g.vo(this.C);this.w&&this.w.removeUpdateListener(this.K);this.w=null;B7.yb.Z.call(this)};
g.h.yO=function(a){this.ka()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ea,this.Ud())};
g.h.Fq=function(a){this.J=l6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,tsa(this));a(b);ssa(this)}else this.D=(0,g.x)(function(){g.vo(this.C);this.D=g.Ea;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,tsa(this));a(c);ssa(this)},this),this.C=g.to((0,g.x)(function(){this.D()},this),100)};
g.h.CE=function(a,b,c){nsa(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Qn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Fq(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Fq(b,c)},this))};g.Qa(C7,y7);C7.prototype.stop=function(){this.Ud()};
C7.prototype.Ys=g.Ea;C7.prototype.Di=function(){g.vo(this.o);this.o=NaN;var a=n6(this.H.Qd(),this.u.label);a?this.Qn(a):this.Ud(Error("No such screen"))};
C7.prototype.Z=function(){g.vo(this.o);this.o=NaN;C7.yb.Z.call(this)};g.Qa(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.sL,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.zz,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.HJ,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ka()||
(chrome.cast.addReceiverActionListener(this.w),asa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.GB,this)),this.A=vsa(this),chrome.cast.setCustomReceivers(this.A,g.Ea,(0,g.x)(function(k){this.Kb("Failed to set initial custom receivers: "+g.Hk(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Kb("Failed to initialize API: "+g.Hk(k));
b(!1)},this))};
g.h.uN=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.A;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=n6(this.u.Qd(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=usa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ea,(0,g.x)(function(e){this.Kb("Failed to set initial custom receivers: "+g.Hk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.Zs(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.vN=function(a){this.ka()?this.Kb("Setting connection data on disposed cast v2"):this.o?this.o.Di(a):this.Kb("Setting connection data without a session")};
g.h.xO=function(){this.ka()?this.Kb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.zz,this),(0,g.x)(this.PL,this))};
g.h.Z=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.GB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.w);var a=Yra,b=g.w("yt.mdx.remote.debug.handlers_");g.bb(b||[],a);g.de(this.o);D7.yb.Z.call(this)};
g.h.Kb=function(a){i7("Controller",a)};
g.h.Az=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.oL=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.A&&this.R("yt-remote-cast2-session-change",this.o.A);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Kb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Kb("Stopping receiver w/o session: "+a.friendlyName)}else this.Kb("onReceiverAction_ called without receiver.")};
g.h.HJ=function(a){if(this.ka())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Kb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Kb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.A)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.A),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Kb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.CE,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Fq,b))};
g.h.zz=function(a){if(!this.ka()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Kb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=n6(this.u.Qd(),c.label);d&&i6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.de(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.Az,this,this.o)),this.o.Di(null));this.o.Ys(a)}}};
g.h.wO=function(){return this.o?this.o.HB():null};
g.h.PL=function(a){this.ka()||(this.Kb("Failed to estabilish a session: "+g.Hk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.sL=function(a){E7("Receiver availability updated: "+a);if(!this.ka()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.GB=function(){this.ka()||(this.A=vsa(this),E7("Updating custom receivers: "+g.Hk(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ea,(0,g.x)(function(){this.Kb("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.vN;D7.prototype.setConnectedScreenStatus=D7.prototype.uN;D7.prototype.stopSession=D7.prototype.xO;D7.prototype.getCastSession=D7.prototype.wO;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Oe=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.C=a.playerTimeAt,this.w=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.A=a.liveIngestionTime,this.B=
!isNaN(this.A))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ea,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ea,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ea,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Oa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ea,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Kb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Kb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Oa(this.setVolume,a,b))};
g.h.BA=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Hk(b.style),g.bc(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Oa(this.BA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Oa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Hk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.CB=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Oa(this.CB,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Oa(this.nextVideo,a,b))};
g.h.tv=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.tv)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.Z=function(){Isa(this);this.w=null;this.B.clear();Y7(this,null);g.Q.prototype.Z.call(this)};
g.h.Qt=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.Za(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.lL=function(a,b){this.R(a,b)};
g.h.oJ=function(a){if(!a)this.Kk(null),Y7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.Kk=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),Jsa(this),this.R("remotePlayerChange")};
g.h.nJ=function(a){a?(Jsa(this),this.R("remotePlayerChange")):this.Kk(null)};
g.h.AJ=function(){var a=Fsa();a&&Y7(this,a)};
g.h.Kb=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;U7(this.Qa,m);this.w="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Hk(l));this.o.connect({method:"setPlaylist",
params:g.Hk(l)},a,Wqa())}else g8("Connecting without params"),this.o.connect({},a,Wqa());Lsa(this)};
g.h.dispose=function(){this.ka()||(this.R("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.Z=function(){i8(this);k8(this);j8(this);g.vo(this.D);this.D=NaN;g.vo(this.G);this.G=NaN;this.A=null;g.ir(this.U);this.U.length=0;this.o.dispose();g.Q.prototype.Z.call(this);this.w=this.C=this.u=this.Qa=this.o=null};
g.h.SD=function(){this.ci(2)};
g.h.sJ=function(){g8("Channel opened");this.K&&(this.K=!1,j8(this),this.J=g.to((0,g.x)(function(){g8("Timing out waiting for a screen.");this.ci(1)},this),15E3));
$qa(Vra(this.o),this.N)};
g.h.pJ=function(){g8("Channel closed");isNaN(this.B)?s6(!0):s6();this.dispose()};
g.h.qJ=function(a){s6();isNaN(this.Oj())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.K=!0,g8("Channel error: "+a+" with reconnection in "+this.Oj()+" ms"),h8(this,2))};
g.h.rJ=function(a){a.params?g8("Received: action="+a.action+", params="+g.Hk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.G)(a,function(c){return new g6(c)});
a=!!g.Va(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Osa(this,a);break;case "loungeScreenDisconnected":g.cb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Osa(this,!1);break;case "remoteConnected":var b=new g6(x6(a.params.device));g.Va(this.u,function(c){return b?c.id==b.id:!1})||Gqa(this.u,b);
break;case "remoteDisconnected":b=new g6(x6(a.params.device));g.cb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Qsa(this,a);break;case "nowPlaying":Ssa(this,a);break;case "onStateChange":Rsa(this,a);break;case "onAdStateChange":Tsa(this,a);break;case "onVolumeChanged":Usa(this,a);break;case "onSubtitlesTrackChanged":Psa(this,a);break;case "nowAutoplaying":Vsa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.w=
a.params.autoplayMode;this.R("autoplayModeChange",this.w);"DISABLED"==this.w&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":Wsa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.jN=function(){if(this.A){var a=this.A;this.A=null;this.Qa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.HD=function(){var a=3;this.ka()||(a=0,isNaN(this.Oj())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.ci=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&s6();Wra(this.o,a);this.dispose()};
g.h.GD=function(){var a=this.Qa;this.A&&(a=this.Qa.clone(),W7(a,this.A,a.index));return X7(a)};
g.h.wN=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.A=b.videoId,g.vo(this.D),this.D=g.to((0,g.x)(this.jN,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&V7(this.Qa)==V7(b)&&g.Hk(this.Qa.o)==g.Hk(b.o)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.y)(c,function(d){this.R(d)},this)};
g.h.gw=function(){var a=this.o.C.id,b=g.Va(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Oj=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.F)():NaN};
g.h.vD=function(){return this.w||"UNSUPPORTED"};
g.h.wD=function(){return this.C||""};
g.h.pO=function(){if(!isNaN(this.Oj())){var a=this.o.u;g.Ym(a.o);a.start()}};
g.h.rN=function(a,b){l8(this,a,b);Nsa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.Ve;f8.prototype.getProxyState=f8.prototype.HD;f8.prototype.disconnect=f8.prototype.ci;f8.prototype.getPlayerContextData=f8.prototype.GD;f8.prototype.setPlayerContextData=f8.prototype.wN;f8.prototype.getOtherConnectedRemoteId=f8.prototype.gw;f8.prototype.getReconnectTimeout=f8.prototype.Oj;f8.prototype.getAutoplayMode=f8.prototype.vD;f8.prototype.getAutoplayVideoId=f8.prototype.wD;f8.prototype.reconnect=f8.prototype.pO;
f8.prototype.sendMessage=f8.prototype.rN;g.r(m8,m7);g.h=m8.prototype;g.h.Qd=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.add=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.yo=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.Z=function(){for(var a=0,b=this.u.length;a<b;++a)this.Xc.$_ubk(this.u[a]);this.u.length=0;this.Xc=null;m7.prototype.Z.call(this)};
g.h.tO=function(){this.R("screenChange")};
g.h.PK=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.uO;v7.prototype.$_gsppc=v7.prototype.FB;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.yo;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.Qd;v7.prototype.$_gos=v7.prototype.EB;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Ve;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.A);g.h=G8.prototype;
g.h.Z=function(){g.A.prototype.Z.call(this);this.w.stop();this.C.stop();this.K.stop();this.S();this.o.unsubscribe("proxyStateChange",this.wz,this);this.o.unsubscribe("remotePlayerChange",this.Nk,this);this.o.unsubscribe("remoteQueueChange",this.Rn,this);this.o.unsubscribe("autoplayUpNext",this.Xy,this);this.o.unsubscribe("previousNextChange",this.sz,this);this.o.unsubscribe("nowAutoplaying",this.oz,this);this.o.unsubscribe("autoplayDismissed",this.Wy,this);this.o=this.B=null};
g.h.Rx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Hm(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.mJ=function(a){this.K.OD(a)};
g.h.VN=function(a){this.Rx("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.OA=function(){var a=this.u.getOption("captions","track");g.Wb(a)||K8(this,a)};
g.h.hz=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.Nk,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.U.start();this.o.subscribe("remotePlayerChange",this.Nk,this)}};
g.h.kK=function(){g.Wb(this.D)||hta(this,this.D);this.G=!1};
g.h.wz=function(a,b){this.C.stop();2==b&&this.MA()};
g.h.Nk=function(){if(J8(this)){this.w.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.PD(8));this.LA();break;case 1085:case 3:I8(this,new g.PD(9));break;case 1083:case 0:I8(this,new g.PD(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.PD(4));break;case 2:I8(this,new g.PD(4));H8(this,V7(a));
break;case -1:I8(this,new g.PD(64));break;case -1E3:I8(this,new g.PD(128,{errorCode:"mdx.remoteerror",errorMessage:"Cette vid\u00e9o ne peut pas \u00eatre visionn\u00e9e \u00e0 distance."}))}a=$7(this.o).o;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,hta(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.U.isActive()||this.rB()}else gta(this)};
g.h.sz=function(){this.u.R("mdxpreviousnextchange")};
g.h.Rn=function(){J8(this)||gta(this)};
g.h.MC=function(){this.o.tv()};
g.h.Xy=function(){};
g.h.oz=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.Wy=function(){this.u.R("mdxautoplaycanceled")};
g.h.zG=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.rB=function(){if(J8(this)){var a=$7(this.o);this.A.Ua(this.N);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.N=this.A.M(this.u,"onVolumeChange",this.hz)}};
g.h.LA=function(){this.w.stop();if(!this.o.ka()){var a=$7(this.o);1==a.playerState&&I8(this,new g.PD(8));H8(this,V7(a));this.w.start()}};
g.h.MA=function(){this.C.stop();this.w.stop();var a=this.o.w.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.S);M8.prototype.B=function(){e6("mdx-privacy-popup-cancel");this.w.hide()};
M8.prototype.D=function(){e6("mdx-privacy-popup-confirm");this.w.hide()};g.r(N8,g.S);N8.prototype.C=function(a){jta(this,a.state)};g.r(O8,g.RP);O8.prototype.N=function(){var a=this.w.getOption("remote","receivers");a&&1<a.length&&!this.w.getOption("remote","quickCast")?(this.G=g.rb(a,this.D,this),g.TP(this,(0,g.G)(a,this.D)),a=this.w.getOption("remote","currentReceiver"),this.je(this.D(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.D=function(a){return a.key};
O8.prototype.we=function(a){return"cast-selector-receiver"==a?"Caster sur\u2026":this.G[a].name};
O8.prototype.Rc=function(a){g.RP.prototype.Rc.call(this,a);this.w.setOption("remote","currentReceiver",this.G[a]);this.B.bb()};g.r(P8,g.$Q);g.h=P8.prototype;
g.h.create=function(){ata(g.ry(this.player.P()));this.w.push(g.Ao("yt-remote-before-disconnect",this.jJ,this));this.w.push(g.Ao("yt-remote-connection-change",this.tL,this));this.w.push(g.Ao("yt-remote-receiver-availability-change",this.uz,this));this.w.push(g.Ao("yt-remote-auto-connect",this.rL,this));this.w.push(g.Ao("yt-remote-receiver-resumed",this.qL,this));this.w.push(g.Ao("mdx-privacy-popup-confirm",this.YM,this));this.w.push(g.Ao("mdx-privacy-popup-cancel",this.XM,this));this.uz()};
g.h.load=function(){this.player.cancelPlayback();g.$Q.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=fta())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.U=a||0,this.player.R("progresssync",a,void 0));ita(this,this.D,this.D);g.yU(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.A=this.u;g.ee(this.B,this.o);this.o=this.B=null;g.$Q.prototype.unload.call(this);g.yU(this.player.app,5);Q8(this)};
g.h.Z=function(){g.Bo(this.w);g.$Q.prototype.Z.call(this)};
g.h.xk=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.Rx.apply(this.B,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.H};
g.h.JD=function(){return this.loaded?this.B.suggestion:null};
g.h.Oe=function(){return this.o?$7(this.o).Oe:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.U};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.T(this.player.P().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.sc():!a.isAdPlaying()&&this.player.sc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.A+T7(a):a.A,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.w?a.w+T7(a):
a.w}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.nG=function(){this.o&&this.o.CB()};
g.h.jJ=function(a){1==a&&(this.N=this.o?$7(this.o):null)};
g.h.tL=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.o=a;this.N=null;b.key!=this.u.key&&(this.A=b,this.load())}else g.de(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.N)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.uz=function(){this.J=[this.u].concat(cta());var a=y8()||this.u;R8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.MM=function(a){!this.K&&g.cE(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.rL=function(){var a=y8();R8(this,a)};
g.h.qL=function(){this.A=y8()};
g.h.YM=function(){this.K=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.XM=function(){this.K=!1;Q8(this);R8(this,this.u);this.A=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Cc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.A:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.oG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ff=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.pR.remote=P8;})(_yt_player);
